"""A small bundled dictionary of extremely common / breached passwords.

This is intentionally compact (a few hundred entries) rather than a full
multi-million-line corpus: the goal is a fast, transparent "is this an obvious
password" check that ships inside the package with no external file. For an
authoritative, exhaustive breach answer the auditor uses the Have I Been Pwned
range API (see :mod:`pwaudit.hibp`).

Source: the entries are drawn from widely published "most common passwords"
lists (e.g. NordPass / SecLists ``10k-most-common``). They are stored lower-cased;
lookups should lower-case the candidate password before checking membership.
"""

from __future__ import annotations

# Curated set of very common passwords (lower-cased). Kept deliberately small.
COMMON_PASSWORDS: frozenset[str] = frozenset(
    {
        # Numeric runs and PINs
        "123456",
        "12345",
        "123456789",
        "12345678",
        "1234567",
        "1234567890",
        "1234",
        "111111",
        "123123",
        "000000",
        "654321",
        "121212",
        "112233",
        "789456",
        "159753",
        "987654321",
        "11111111",
        "0000",
        "1111",
        "2222",
        "7777",
        "1212",
        "1q2w3e4r",
        "1q2w3e",
        "1qaz2wsx",
        "zaq12wsx",
        # Words
        "password",
        "password1",
        "password123",
        "passw0rd",
        "p@ssw0rd",
        "p@ssword",
        "pass",
        "passwd",
        "admin",
        "administrator",
        "root",
        "user",
        "guest",
        "login",
        "letmein",
        "welcome",
        "welcome1",
        "welcome123",
        "secret",
        "default",
        "changeme",
        "test",
        "test123",
        "demo",
        "temp",
        "access",
        "master",
        "superman",
        "batman",
        "spiderman",
        "iloveyou",
        "iloveu",
        "trustno1",
        "sunshine",
        "princess",
        "freedom",
        "whatever",
        "shadow",
        "monkey",
        "dragon",
        "football",
        "baseball",
        "soccer",
        "hockey",
        "basketball",
        "golfer",
        "hunter",
        "buster",
        "ranger",
        "ginger",
        "pepper",
        "cookie",
        "summer",
        "winter",
        "autumn",
        "spring",
        "computer",
        "internet",
        "samsung",
        "google",
        "facebook",
        "starwars",
        "matrix",
        "ninja",
        "mustang",
        "harley",
        "ferrari",
        "corvette",
        "porsche",
        "tigger",
        "charlie",
        "robert",
        "thomas",
        "michael",
        "jordan",
        "jennifer",
        "michelle",
        "daniel",
        "ashley",
        "andrew",
        "joshua",
        "amanda",
        "nicole",
        "hannah",
        "love",
        "money",
        "freedom1",
        "qwerty",
        "qwertyuiop",
        "qwerty123",
        "qweasd",
        "asdfgh",
        "asdfghjkl",
        "zxcvbn",
        "zxcvbnm",
        "qazwsx",
        "qazwsxedc",
        "abc123",
        "abcd1234",
        "abcdef",
        "abcdefg",
        "a1b2c3",
        "aaaaaa",
        "asdf1234",
        "letmein123",
        "admin123",
        "root123",
        "pa55word",
        "pa55w0rd",
        "passwordpassword",
        "qwerty1",
        "111222",
        "google123",
        "starwars1",
    }
)


def is_common_password(password: str) -> bool:
    """Return ``True`` if *password* is in the bundled common-password set.

    The comparison is case-insensitive: the candidate is lower-cased before the
    membership test, matching how the list itself is stored.
    """
    return password.lower() in COMMON_PASSWORDS
